apiVersion: v1
kind: Service
metadata:
  name: movie-search-app
  labels:
    app: movie-search-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: movie-search-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-search-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-search-app
  template:
    metadata:
      name: movie-search-app
      labels:
        app: movie-search-app
    spec:
      containers:
        - name: movie-search-app
          image: movie-search:2.4.4
          imagePullPolicy: Never
          env:
          - name: BW_LOGLEVEL
            value: "ERROR"
          - name: BW_JAVA_OPTS
            value: "-Dbw.engine.opentracing.enable=true"
          - name: BW_PROFILE
            value: "docker"
          - name: APP_CONFIG_PROFILE
            value: "docker"
          - name: CONSUL_SERVER_URL
            value: "http://10.96.36.53:8500"
          - name: BW_APP_MONITORING_CONFIG
            value: "{\"url\" : \"http://10.100.129.64:80\"}"
          ports:
            - containerPort: 8080