apiVersion: v1
kind: Service
metadata:
  name: bwcemon
spec:
  type: NodePort
  selector:
    app: bwcemon
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwcemon
spec:
  selector:
    matchLabels:
      app: bwcemon
  template:
    metadata:
      labels:
        app: bwcemon
    spec:
      containers:
      - name: bwcemon
        image: bwcemon:2.4.4
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "512Mi"
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          - name: PERSISTENCE_TYPE
            value: postgres
          - name: DB_URL
            value: postgresql://bwuser:bwuser@10.97.114.64:5432/bookstore

